name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run TypeScript check
      run: npx tsc --noEmit
      
    - name: Run ESLint
      run: npx eslint src --ext .ts,.tsx --max-warnings 0
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      
    - name: Build application
      run: npm run build
      env:
        REACT_APP_ENVIRONMENT: production
    
    - name: Build crew generator
      run: |
        cd crew-generator
        npm ci
        npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_PUBLIC_BASE_PATH: /crew/
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          build/
          crew-generator/dist/

  build-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for staging with banner
      run: npm run build
      env:
        REACT_APP_ENVIRONMENT: staging
    
    - name: Build crew generator for staging
      run: |
        cd crew-generator
        npm ci
        npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_PUBLIC_BASE_PATH: /crew/
        
    - name: Upload staging build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: staging-build-files
        path: |
          build/
          crew-generator/dist/

  deploy-staging:
    needs: build-staging
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Download staging build artifacts
      uses: actions/download-artifact@v4
      with:
        name: staging-build-files
        path: build/
        
    - name: Deploy to staging
      env:
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        STAGING_SFTP_USERNAME: ${{ secrets.STAGING_SFTP_USERNAME }}
        STAGING_SFTP_HOST: ${{ secrets.STAGING_SFTP_HOST }}
        STAGING_SFTP_PATH: ${{ secrets.STAGING_SFTP_PATH }}
      run: |
        echo "🚀 Deploying to staging environment..."
        # Install sshpass for automated SFTP
        sudo apt-get update && sudo apt-get install -y sshpass
        
        # Debug connection info (without password)
        echo "Connecting to: ${STAGING_SFTP_USERNAME}@${STAGING_SFTP_HOST}"
        echo "Target path: ${STAGING_SFTP_PATH}"
        
        # Deploy main site to staging subdomain
        sshpass -p "${SFTP_PASSWORD}" scp -P 22212 -o StrictHostKeyChecking=no -o Compression=yes -r build/* "${STAGING_SFTP_USERNAME}@${STAGING_SFTP_HOST}:${STAGING_SFTP_PATH}"
        
        # Deploy crew generator to /crew subdirectory (check if dist exists first)
        if [ -d "crew-generator/dist" ]; then
          sshpass -p "${SFTP_PASSWORD}" scp -P 22212 -o StrictHostKeyChecking=no -o Compression=yes -r crew-generator/dist/* "${STAGING_SFTP_USERNAME}@${STAGING_SFTP_HOST}:${STAGING_SFTP_PATH}/crew/"
        else
          echo "⚠️ crew-generator/dist not found, checking alternative paths..."
          find . -name "dist" -type d
          ls -la
        fi
        
        echo "🎉 Staging deployment complete!"
        echo "View at: https://${{ secrets.STAGING_DOMAIN }}"

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: build/
        
    - name: Deploy to production
      env:
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_PATH: ${{ secrets.SFTP_PATH }}
      run: |
        echo "🚀 Deploying to production..."
        # Install sshpass for automated SFTP
        sudo apt-get update && sudo apt-get install -y sshpass
        
        # Debug connection info (without password)
        echo "Connecting to: ${SFTP_USERNAME}@${SFTP_HOST}"
        echo "Target path: ${SFTP_PATH}"
        
        # Deploy main site to production
        sshpass -p "${SFTP_PASSWORD}" scp -P 22212 -o StrictHostKeyChecking=no -o Compression=yes -r build/* "${SFTP_USERNAME}@${SFTP_HOST}:${SFTP_PATH}"
        
        # Deploy crew generator to /crew subdirectory (check if dist exists first)
        if [ -d "crew-generator/dist" ]; then
          sshpass -p "${SFTP_PASSWORD}" scp -P 22212 -o StrictHostKeyChecking=no -o Compression=yes -r crew-generator/dist/* "${SFTP_USERNAME}@${SFTP_HOST}:${SFTP_PATH}/crew/"
        else
          echo "⚠️ crew-generator/dist not found, checking alternative paths..."
          find . -name "dist" -type d
          ls -la
        fi
        
        echo "🎉 Production deployment complete!"
        echo "View at: https://${{ secrets.PRODUCTION_DOMAIN }}"
